import Navebar from '@/components/navebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import Line from '@/components/line'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FAMZ',
  description: 'Generated by Daniyal',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-mywhite`}>
        <Navebar/>
        <Line/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
